//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBoarsClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientId { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public string PassportNumSerial { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Gender { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string MedCardNum { get; set; }
        public System.DateTime MedCardDate { get; set; }
        public System.DateTime LastVizitDate { get; set; }
        public Nullable<System.DateTime> NextVizitDate { get; set; }
        public string PolisNum { get; set; }
        public System.DateTime PolisDate { get; set; }
        public string Diagnose { get; set; }
        public string MedicalHistory { get; set; }
    }
}
